repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
          - "--exclude-files"
          - "^(containers/(docker|podman|singularity)/OCDocker\\.cfg\\..*|OCDocker\\.(cfg|yml)\\.example)$"
