name: my_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - biopython
  - cupy
  - deap
  - h5py
  - joblib
  - matplotlib-base
  - numpy
  - openbabel
  - optuna
  - pandas
  - rdkit
  - scikit-learn
  - scipy
  - seaborn
  - six
  - spyrmsd
  - sqlalchemy
  - sqlalchemy-utils
  - pytorch
  - tqdm
  - xgboost
