name: ocdocker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.11
  - pip

  # core data science
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib-base
  - seaborn
  - ipython
  - tqdm
  - biopython
  - h5py
  - xgboost
  - optuna
  - optuna-dashboard
  - pingouin
  - tensorboard

  # chemistry / docking
  - rdkit
  - openbabel
  - oddt
  - spyrmsd

  # Snakemake
  - bioconda::snakemake-minimal
  # - bioconda::snakemake

  # GPU (se precisa)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  # I/O & cloud, DB
  - requests
  - boto3
  - google-api-python-client
  - google-cloud-storage
  - dropbox
  - paramiko
  - pysftp
  - mysqlclient
  - sqlalchemy
  - graphviz
